pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = credentials('github-creds')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: env.GITHUB_CREDENTIALS, url: 'https://github.com/CiiruNgunjiri/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv && \
                . venv/bin/activate && \
                pip3 install -r messaging_app/requirements.txt && \
                pip3 install pytest pytest-cov
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate && \
                pytest messaging_app --junitxml=results.xml
                '''
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'results.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("linda575/messaging_app:${env.BUILD_NUMBER}")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-creds') {
                        dockerImage.push()
                    }
                }
            }
        }
    }

   
    // No automatic trigger; manual run only
   

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}
